#!/usr/bin/env tsx
// Build the TON Jetton master BOC from Acton's built-in `jetton` template,
// without keeping any source under version control.
//
// Flow:
//   1. Create a temp scratch dir
//   2. `acton new . --template jetton` (materialize template files there)
//   3. `acton build` (produce build/JettonMinter.json)
//   4. Extract code_boc64 + hash → web/src/chains/ton/contracts/jetton-codes.ts
//   5. Remove the scratch dir
//
// Pinned to the Acton version that produced the committed BOC. Bump
// EXPECTED_ACTON_VERSION when you intentionally adopt a newer template.

import { execSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_PATH = join(REPO_ROOT, "web/src/chains/ton/contracts/jetton-codes.ts");
const EXPECTED_ACTON_VERSION = "1.0.0";

// Acton installer puts the binary in ~/.acton/bin but doesn't always end up on
// non-interactive shells' PATH. Prepend it defensively.
const ACTON_BIN = join(process.env.HOME ?? "", ".acton/bin");
const PATH = `${ACTON_BIN}:${process.env.PATH ?? ""}`;

function sh(cmd: string, cwd: string): string {
  return execSync(cmd, { cwd, env: { ...process.env, PATH }, encoding: "utf8" });
}

function checkActon(): void {
  let v: string;
  try {
    v = sh("acton --version", REPO_ROOT).trim();
  } catch {
    console.error(
      "[build-ton] acton CLI not found. Install with:\n" +
        "  curl -LsSf https://github.com/ton-blockchain/acton/releases/latest/download/acton-installer.sh | sh",
    );
    process.exit(1);
  }
  console.log(`[build-ton] ${v}`);
  if (!v.includes(EXPECTED_ACTON_VERSION)) {
    console.warn(
      `[build-ton] WARNING: pinned to acton ${EXPECTED_ACTON_VERSION}, got "${v}". ` +
        "BOC may differ from the previously committed one.",
    );
  }
}

function main(): void {
  checkActon();

  const scratch = mkdtempSync(join(tmpdir(), "tokenforge-jetton-"));
  try {
    console.log(`[build-ton] scaffolding into ${scratch}`);
    sh(
      "acton new . --template jetton --name tokenforge-jetton --license MIT",
      scratch,
    );

    console.log("[build-ton] building");
    sh("acton build", scratch);

    const artifactPath = join(scratch, "build/JettonMinter.json");
    const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as {
      code_boc64: string;
      hash: string;
    };

    const banner = `// AUTO-GENERATED by scripts/build-ton.ts — do not hand-edit.
// Source: Acton ${EXPECTED_ACTON_VERSION} built-in "jetton" template, scaffolded
// ephemerally and compiled at build time. The repo intentionally does NOT
// vendor the Tolk source — this BOC is the only thing we depend on.
//
// Regenerate:  pnpm ton:build
//
// Storage layout, opcodes, and message shapes used by MintPageVM.ts assume
// this template (TEP-74 + 2-step admin handoff + sharded wallet deploy).
`;

    const out =
      banner +
      `\nexport const JETTON_MASTER_CODE_BOC = "${artifact.code_boc64}";\n` +
      `export const JETTON_MASTER_CODE_HASH = "${artifact.hash}";\n`;

    mkdirSync(dirname(OUT_PATH), { recursive: true });
    writeFileSync(OUT_PATH, out);

    console.log(`[build-ton] code hash: ${artifact.hash}`);
    console.log(`[build-ton] wrote ${OUT_PATH}`);
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

main();
