#!/usr/bin/env tsx
// Build the Sui Move coin template and extract its compiled bytecode into
// the frontend.
//
// Flow:
//   1. cd contracts/sui/template && sui move build
//   2. Read build/.../bytecode_modules/token.mv
//   3. Write hex + dependencies + placeholder values to
//      web/src/chains/sui/contracts/coin-template.ts
//
// The frontend uses @mysten/move-bytecode-template to patch the placeholders
// at publish time, so the only thing that needs regenerating after a Move
// source change is this one file. Run `pnpm sui:build` to refresh.

import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TEMPLATE_DIR = join(REPO_ROOT, "contracts/sui/template");
const MODULE_PATH = join(
  TEMPLATE_DIR,
  "build/tokenforge_coin_template/bytecode_modules/token.mv",
);
const OUT_PATH = join(
  REPO_ROOT,
  "web/src/chains/sui/contracts/coin-template.ts",
);

// Placeholders MUST stay in sync with contracts/sui/template/sources/token.move.
const PLACEHOLDERS = {
  decimals: 222,
  symbol: "SYM_PH",
  name: "NAME_PLACEHOLDER______________",
  description: "DESCRIPTION_PLACEHOLDER____________________",
  initialSupply: "1234567890123",
};

function sh(cmd: string, cwd: string): void {
  execSync(cmd, { cwd, stdio: "inherit" });
}

function main(): void {
  console.log("[build-sui] sui move build");
  sh("sui move build", TEMPLATE_DIR);

  const bytecode = readFileSync(MODULE_PATH);
  const hex = bytecode.toString("hex");

  const banner = `// AUTO-GENERATED by scripts/build-sui.ts — do not hand-edit.
// Source: contracts/sui/template/sources/token.move (compiled by 'sui move build').
// Frontend patches placeholders via @mysten/move-bytecode-template before publish.
//
// Regenerate:  pnpm sui:build
`;

  const body = `\nexport const COIN_TEMPLATE_MODULE_HEX = "${hex}";

// Sui Framework (0x2) + Move Stdlib (0x1) — constants on every Sui network
// (testnet, mainnet, devnet, localnet). Bridge / SuiSystem omitted because
// the template doesn't depend on them.
export const COIN_TEMPLATE_DEPENDENCIES = ["0x1", "0x2"];

// Placeholders inside the compiled bytecode. Patched by sui-coin-contract.ts
// at publish time. Keep in sync with sources/token.move.
export const COIN_TEMPLATE_PLACEHOLDERS = {
  decimals: ${PLACEHOLDERS.decimals},
  symbol: ${JSON.stringify(PLACEHOLDERS.symbol)},
  name: ${JSON.stringify(PLACEHOLDERS.name)},
  description: ${JSON.stringify(PLACEHOLDERS.description)},
  initialSupply: ${PLACEHOLDERS.initialSupply}n,
} as const;
`;

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, banner + body);
  console.log(`[build-sui] wrote ${OUT_PATH} (${hex.length / 2} bytes)`);
}

main();
